apiVersion: apps/v1
kind: Deployment

metadata:
  name: blog

spec:

  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      labels:
        app: blog

    spec:
      containers:
      - name: blog
        image: blog
        imagePullPolicy: Never
        env:
        - name: MODEL_NAME
          value: stablelm2
        - name: MODEL_HOST
          value: http://model:11434
        - name: DB_HOST
          value: blog-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"
