apiVersion: apps/v1
kind: Deployment

metadata:
  name: model

spec:

  selector:
    matchLabels:
      app: model

  template:
    metadata:
      labels:
        app: model

    spec:
      containers:
      - name: model
        image: model
        imagePullPolicy: Never
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: "512Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"
