apiVersion: apps/v1
kind: Deployment

metadata:
  name: blog-db

spec:

  selector:
    matchLabels:
      app: blog-db

  template:
    metadata:
      labels:
        app: blog-db

    spec:
      volumes:
      - name: postgres-pv-storage
        persistentVolumeClaim:
          claimName: blog-db
      containers:
      - name: blog-db
        image: postgres:alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD 
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_USERNAME
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: blog-db
  labels:
    app: blog-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: blog-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-db
spec:
  storageClassName: blog-db-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-db
spec:
  storageClassName: blog-db-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
