name: 'Deploy'
description: 'Deploy to kube'

inputs:
  ARGO_CD_APP_NAME: 
    required: true
  ARGOCD_SERVER:
    required: true
  ARGOCD_USERNAME:
    required: true
  ARGOCD_PASSWORD:
    required: true
runs:
  using: "composite"
  image: argoproj/argocd
  variables:
    GIT_STRATEGY: none
    ARGOCD_SERVER: ${{ inputs.ARGOCD_SERVER }}
    ARGOCD_USERNAME: ${{ inputs.ARGOCD_USERNAME }}
    ARGOCD_PASSWORD: ${{ inputs.ARGOCD_PASSWORD }}
  steps:
    - name: argocd-login
      shell: bash
      run: argocd login "${ARGOCD_SERVER}" --insecure --username "${ARGOCD_USERNAME}" --password "${ARGOCD_PASSWORD}"
    - name: restart-app
      shell: bash
      run: |
        argocd app actions run "$ARGOCD_APP_NAME" restart --kind Deployment |& tee response.txt
        cat response.txt
        if [ -s response.txt ]; then exit 1; fi
