name: 'Deploy'
description: 'Deploy to kube'

inputs:
  ARGO_CD_APP_NAME: 
    required: true
  ARGOCD_SERVER:
    required: true
  ARGOCD_USERNAME:
    required: true
  ARGOCD_PASSWORD:
    required: true
runs:
  using: "docker"
  image: docker://argoproj/argocd
  steps:
    - name: argocd-login
      shell: bash
      run: argocd login "${{ inputs.ARGOCD_SERVER }}" --insecure --username "${{ inputs.ARGOCD_USERNAME }}" --password "${{ inputs.ARGOCD_PASSWORD }}"
    - name: restart-app
      shell: bash
      run: |
        argocd app actions run "${{ inputs.ARGO_CD_APP_NAME }}" restart --kind Deployment |& tee response.txt
        cat response.txt
        if [ -s response.txt ]; then exit 1; fi
