replicaCount: 1

image:
  repository: blog
  pullPolicy: Never
  tag: "latest"
  
imagePullSecrets: []


service:
  type: ClusterIP
  port: 8000

env:
  modelName: stablelm2
  modelHost: http://model:11434
  dbHost: blog-db

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
    - host: blog.app
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

labels:
  app: blog

selectorLabels:
  app: blog
