replicaCount: 3

image:
  repository: model
  pullPolicy: None
  tag: "latest"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 11434

resources:
  limits:
    memory: "1024Mi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

labels:
  app: model

selectorLabels:
  app: model
